services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_URL=redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - data01:/usr/share/redis/data

volumes:
  data01:
    driver: local
