name: Check GTFS schedule version

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - main
      - db-import-script

env:
  PREV_LAST_MODIFIED: ${{ secrets.GTFS_LAST_MODIFIED }}

jobs:
  get_header:
    runs-on: ubuntu-latest
    outputs:
      lastModified: ${{ steps.setlastModified.outputs.lastModified }}
    steps:
      - name: Make get request
        id: getRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://www.transportforireland.ie/transitData/Data/GTFS_All.zip"
          method: "GET"
      - name: Set last modified
        id: setlastModified
        run: |
          echo "lastModified='${{ fromJson(steps.getRequest.outputs.headers).last-modified }}'" >> "$GITHUB_OUTPUT"
      - name: test
        run: echo $lastModified

  test:
    needs: get_header
    runs-on: ubuntu-latest
    steps:
      - env:
          output1: ${{needs.get_header.outputs.lastModified}}
        run: echo "$output1"

  # call_deploy:
  #   needs:
  #     get_header
  #   env: ${{needs.get_header.outputs.output1}}

  # uses: ./.github/workflows/deploy.yml
