name: Deploy to Fly

on:
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg "${env.LAST_MODIFIED_HEADER}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          LAST_MODIFIED_HEADER: ${{ vars.GTFS_LAST_MODIFIED }}
